### ISSUE TITLE
Unable to build the app

### ISSUE THREAD

**Issue by pbca26** [Zondax/ledger-zcash#11]
I'm trying to build the app but it fails on my end after running a few steps on docker image for some reason. Any clues?

```
TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=1.6.1
BOLOS_ENV=/opt/bolos
BOLOS_ENV is /opt/bolos
cd rust && CARGO_HOME="/project/app/rust/.cargo" cargo fmt
/bin/bash: cargo: command not found
make[1]: *** [Makefile:156: rust] Error 127
make[1]: Leaving directory '/project/app'
make: *** [Makefile:28: default] Error 2
make: Leaving directory '/project'
make: *** [build] Error 2
```

**Comment by pbca26** [comment]
I've got a couple of questions as well
Q1) How to specify build for Nano X? I've tried to run this command to no avail TARGET_NAME="TARGET_NANOX" make
I see that Nano X SDK is not included in git submodules so I assume I'll need to add it manually.

Q2) Shielded address derivation takes about 60 seconds on my Nano S. Will it be faster on Nano X since it has better specs?

**Comment by jleni** [comment]
The latest update resolves these issues.
With respecto to time/performance, Nano X and Nano S plus are much better but still it will not be instantaneous.
