### ISSUE TITLE
Possible bug in ZIP 32 Derivation

### ISSUE THREAD

**Issue by hhanh00** [Zondax/ledger-zcash#44]
In `derive_zip32_child_fromseedandpath_ida`, the exk updated by `update_exk_zip32` uses a dummy `ask` and `nsk`.
If I replace them with the real ask, nsk, I get child keys that match `librustzcash` implementation:

```
    let master = ExtendedSpendingKey::master(&seed);
    let path = [
        ChildIndex::Hardened(32),
        ChildIndex::Hardened(133),
        ChildIndex::Hardened(1000),
    ];
    let sk = ExtendedSpendingKey::from_path(&master, &path);
    let (_, pa) = sk.default_address();
    let address = encode_payment_address(MainNetwork.hrp_sapling_payment_address(), &pa);
```

FYI
![image](https://user-images.githubusercontent.com/222239/159764302-1c09e478-4518-4d5e-bfae-9bf1e3b5d619.png)

**Comment by jleni** [comment]
I think this was a temporary test, right @IdaTucker ? 

Can we close this issue?
Is this still relevant?

**Comment by IdaTucker** [comment]
Indeed, derive_zip32_child_fromseedandpath_ida was just created temporariky for testing purposes. It no longer exists. Sorry for the confusion!
