### ISSUE TITLE
Add support for ZIP 313

### ISSUE THREAD

**Issue by nighthawk24** [Zondax/ledger-zcash#6]
ZIP 313 changes the default/conventional fee for shielded transactions from 10,000 zats to 1,000 zats
https://github.com/zcash/zips/pull/408

To implement this change, clients are recommended to change the default fee from 10,000 to 1,000 zats for shielded transactions.

Activation:
* The new default fee of 0.00001 or 1000 zats must start activation at block 1,080,000
 * With a grace period of ~4 weeks (block 1,120,000) to upgrade to the reduced default transaction fee for zcashd and core clients used by exchanges & service providers.

The implementation to activate the new fee can start anytime from the start to the end of the 4 week transition period outside which the shielded transaction fees will stand out from the updated light client fees of 1000 zats.

**Comment by leongb** [comment]
This is supported in milestone 3! https://github.com/Zondax/ledger-zcash/blob/master/app/src/crypto.c#L313-L316
